### PR TITLE
Added radio button

### PR DESCRIPTION
**Pull request by sivasuriyankumarasamy**

### CODE REVIEW

**Comment by GingerKiwi** [comment]
Hi Sivasuriyan, 
Could you do two quick things please?:

1) Rename radioGroup to radio-group . 
I'll add naming conventions in the CONTRIBUTING.md file this week.

2) Fix the conflicts with the first accepted PR. 
I'm working on managing code conflicts as a maintainer, and will figure out how this will work for this repo asap.

**Comment by sivasuriyankumarasamy** [comment]
Hi @GingerKiwi ,

1. Updated radio-button name
2. resolved conflict.

Please add hacktoberfest-accepted label in this PR.
Thanks.

**Review by GingerKiwi — APPROVED** [review]
Thank you for being so quick!

**Review by GingerKiwi — COMMENTED** [review]
Thank you. I'm leaving an approving review for Hacktoberfest. 
There's some code conflict so it can't be merged just yet.

**Pull request merged**
