### PR TITLE
create RESOURCES-FOR-NEW-DEVS.md 

### PR DESCRIPTION
**Pull request by Mirza-Hassan**
created RESOURCES-FOR-NEW-DEVS.md file

### CODE REVIEW

**Comment by GingerKiwi** [comment]
Hi Miza,
Thanks for starting on this PR.
You have the Table of Contents done, but the document needs to be 7 pages long.
Pages 2-7 have one single level one heading at the top.
I'll be checking this repo again in approximately 12 hours.

**Comment by Mirza-Hassan** [comment]
@GingerKiwi sure, I will look into it

**Comment by GingerKiwi** [comment]
For each page:
- [ ] 5 underscores ' _____ '
- [ ] press enter 
- [ ] then # Heading Name
- [ ] Leave a blank of about 10 lines until the next 5 underscores

**Comment by Mirza-Hassan** [comment]
@GingerKiwi I have updated the PR, please review it again.

**Comment by Mirza-Hassan** [comment]
@GingerKiwi It's the last day of `hacktoberfest` PR is still open, can you merge this PR?

**Comment by GingerKiwi** [comment]
Hi Miza,
Thanks for giving it a go.

It should be different pages within the same file RESOURCES-FOR-NEW-DEVS.md, not new files.

Like different headings in an essay written in Word or Google Docs.
The goal is to create a document with the same outline structure as [ALICE-REFERENCES.md](https://github.com/GingerKiwi/alice-game/blob/main/ALICE-REFERENCES.md)
Hopefully using that as an example will help.

I'll be checking in again in about 2.5-3hours for any PRs.

**Comment by Mirza-Hassan** [comment]
@GingerKiwi I have done the changes, can you please review it again?

**Review by GingerKiwi — APPROVED** [review]
Wonderful. 
Thanks for being persistent Mirza!
Let me know if you'd like to continue to contribute a couple of times a month. 
Cheers,
Liz

**Pull request merged**
